events{}

http {
  # 👉 Aumenta el tamaño de buffer para encabezados grandes
    large_client_header_buffers 4 16k;

    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /etc/nginx/html/ng-microservices-demo-client;
            try_files $uri $uri/ /index.html =404;
        }
    }
}
